[theme]

# Color primario para widgets interactivos
primaryColor="#060A24"

# Color de fondo principal de la aplicación
backgroundColor="#E3DC1C"

# Color de fondo secundario (usado en barras laterales y algunos contenedores)
secondaryBackgroundColor="#F0F2F6"

# Color principal del texto
textColor="#31333F"

# Color de la fuente (opcional, pero bueno tenerlo)
font="sans serif"
