[theme]

# Color primario para widgets interactivos
primaryColor="#171603"

# Color de fondo principal de la aplicación
backgroundColor="#171603"

# Color de fondo secundario (usado en barras laterales y algunos contenedores)
secondaryBackgroundColor="#171603"

# Color principal del texto
textColor="#31333F"

# Color de la fuente (opcional, pero bueno tenerlo)
font="sans serif"
